description: >
  Набор имен процессов Windows и Linux, относящихся к корпоративным VPN-клиентам.
  Правило разработано для обеспечения корректной работы данных приложений при их 
  параллельном запуске с ядром Mihomo, предотвращая конфликты перехвата трафика.
author:
  username: Oidaho
  github: https://github.com/Oidaho