behavior: classical
description: >
  Правило, включающее в себя имена процессов VPN-клиентов, которые могут запускаться параллельно с Mihomo.
  Как правило, имена процессов, включенные в это правило, относятся к корпоративным VPN-клиентам.
