description: >
  Список идентификаторов Android-пакетов, соответствующих популярным приложениям Китая. 
  Используется для прямой маршрутизации трафика мобильных приложений в обход прокси-сервера.
  Китайские приложения катигорически не приемлят использование VPN.
author:
  username: Oidaho
  github: https://github.com/Oidaho