description: >
  Набор доменных имен, заблокированных на уровне сетевого провайдера Vladlink. 
  Правило предназначено для исключения данных ресурсов из маршрутизации.
author:
  username: Oidaho
  github: https://github.com/Oidaho