name: Release rule-sets

on:
  workflow_run:
    workflows:
      - Compile Mihomo rules
    types:
      - completed

permissions:
  contents: write

jobs:
  create_release:
    name: Create release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          path: downloads

      - name: List artifacts
        run: |
          find downloads -maxdepth 1 | sort

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: latest
          draft: false
          prerelease: false
          files: |
            downloads/*
